# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 09:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('variants', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('gap_start', models.PositiveSmallIntegerField()),
                ('gap_end', models.PositiveSmallIntegerField()),
                ('order', models.IntegerField(db_index=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.PositiveSmallIntegerField()),
                ('variant_selected', models.NullBooleanField()),
                ('time', models.IntegerField(null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='UserCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Corpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercorpus',
            unique_together=set([('user', 'corpus')]),
        ),
    ]
